services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
      - mysql
    command: sh -c "
      npx sequelize-cli db:migrate &&
      npx sequelize-cli db:seed:all &&
      node app.js
      "
    restart: always

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

  mysql:
    image: mysql:8
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: