# services:
#    app:
#     build: .
#     ports:
#       - "3000:3000"
#     env_file:
#       - .env
#     depends_on:
#       - redis
#       - mysql
#     command: [ "npm", "run", "dev" ]
#     restart: always

#    redis:
#     image: redis:alpine
#     ports:
#       - "6379:6379"
#     restart: always
#     healthcheck:
#       test: ["CMD", "redis-cli", "ping"]
#       interval: 5s
#       timeout: 5s
#       retries: 5

#    mysql:
#     image: mysql:8
#     ports:
#       - "3307:3306"
#     env_file:
#       - .env
#     volumes:
#       - mysql_data:/var/lib/mysql
#     restart: always

# volumes:
#   mysql_data: