# services:
#    app:
#     build: .
#     ports:
#       - "3000:3000"
#     environment:
#     DB_HOST: db
#     depends_on:
#       - redis
#       - mysql
#     command: [ "node", "app.js" ]
#     restart: always

#   redis:
#     image: redis:alpine
#     ports:
#       - "6379:6379"
#     restart: always

#   mysql:
#     image: mysql:8
#     ports:
#       - "3307:3306"
#     env_file:
#       - .env
#     volumes:
#       - mysql_data:/var/lib/mysql
#     restart: always

# volumes:
#   mysql_data: